spring:
  application:
    name: alibi

  profiles:
    default: local

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

  docker:
    compose:
      # docker-compose file is meant to be always started manually
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
