spring:

  application:
    name: alibi

  datasource:
    url: jdbc:postgresql://localhost:5432/alibi
    username: alibi
    password: alibi

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml