spring:
  application:
    name: alibi

  profiles:
    default: local

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  docker:
    compose:
      # docker-compose file is meant to be always started manually
      enabled: false
