
### get all people as admin
GET http://localhost:8080/api/person
Accept: application/json
Authorization: Bearer {{admin_token}}

### get all people as crew manager
GET http://localhost:8080/api/person
Accept: application/json
Authorization: Bearer {{manager_token}}

### create person as admin
POST http://localhost:8080/api/person
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "John Doe",
  "phone": "+420 736 123 456"
}

> {% client.global.set("person_id", response.body.id); %}

### get person detail as admin
GET http://localhost:8080/api/person/{{person_id}}
Accept: application/json
Authorization: Bearer {{admin_token}}

### get person detail as crew manager
GET http://localhost:8080/api/person/{{person_id}}
Accept: application/json
Authorization: Bearer {{manager_token}}
