
### get a page of all items (unsecured)
GET http://localhost:8080/api/item?page=0&size=20&sort=label,asc
Content-Type: application/json

### get a filtered page of tools (unsecured)
GET http://localhost:8080/api/item?category=TOOL&page=0&size=10
Content-Type: application/json

### create item
POST http://localhost:8080/api/item
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "label": "Field radio",
  "category": "TOOL"
}
