
### create person
POST http://localhost:8080/api/person
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "John Doe",
  "phone": "+420 736 123 456"
}
