
### get operation summaries as admin
GET http://localhost:8080/api/operation
Accept: application/json
Authorization: Bearer {{admin_token}}

### get operation summaries as crew manager
GET http://localhost:8080/api/operation
Accept: application/json
Authorization: Bearer {{manager_token}}


### create operation
POST http://localhost:8080/api/operation
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{manager_token}}

{
  "codeName": "Operation Harambe",
  "crewSizeLimit": 5
}

> {% client.global.set("operation_id", response.body.id); %}

### get operation by id
GET http://localhost:8080/api/operation/{{operation_id}}
Accept: application/json
Authorization: Bearer {{manager_token}}

### add crew member
POST http://localhost:8080/api/operation/{{operation_id}}/crew-member
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{manager_token}}

{
  "personId": "{{person_id}}"
}

### remove crew member
DELETE http://localhost:8080/api/operation/{{operation_id}}/crew-member/{{person_id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{manager_token}}
