
### list person names (unauthenticated)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query PersonNames { people { name } }"
}

### list person names and phones (unauthenticated)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query PeopleSummaries { people { id name phone } }"
}

### get person (unauthenticated)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query PersonDetails($id: ID!) { person(id: $id) { id name phone } }",
  "variables": {
    "id": "{{person_id}}"
  }
}

### get person (unauthenticated)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "{ person(id: \"00000000-0000-0000-0000-000000000000\") { id name phone } }"
}
